// <auto-generated>
//     Gerado pelo DASE a partir do modelo ORM. NÃO EDITE ESTE ARQUIVO.
//     Alterações feitas aqui se perdem na próxima geração — a fonte da verdade é o .dsorm.
//     Arquivo com sufixo .Design é parcial: o que for escrito à mão vai no arquivo de mesmo
//     nome sem o sufixo. Os demais são gerados por inteiro e não admitem customização.
// </auto-generated>
