import * as vscode from "vscode";
import { GetLogService } from "./LogService";

/**
 * Torna SOMENTE-LEITURA, no editor do VS Code, os arquivos GERADOS pelo DASE — os que trazem o
 * marcador `<auto-generated>` no cabeçalho que o `_Header.tpl` injeta. Assim uma edição à mão num
 * arquivo que a próxima geração sobrescreveria é barrada na origem, antes de virar trabalho
 * perdido. Os parciais escritos à mão (o arquivo de mesmo nome SEM o sufixo `.Design`) não têm o
 * marcador e continuam editáveis.
 *
 * O bloqueio é "read-only na SESSÃO": não mexe no arquivo em disco nem nas permissões dele —
 * portanto não atrapalha a regeneração nem o git —, e o usuário pode destravar pontualmente pelo
 * cadeado do editor se realmente precisar. Reaplica-se sempre que o arquivo volta a ser o ativo.
 */
export class XGeneratedFileGuard {
    /** Marcador convencional de código gerado, presente em todo arquivo que o DASE emite. */
    private static readonly MARKER = /<auto-generated/i;
    /** O cabeçalho fica nas primeiras linhas — ler só o começo evita varrer arquivos grandes. */
    private static readonly HEAD = 2000;
    /** Comando do VS Code que marca o editor ativo como somente-leitura durante a sessão. */
    private static readonly READONLY_COMMAND = "workbench.action.files.setActiveEditorReadonlyInSession";

    private readonly _Disposables: vscode.Disposable[] = [];

    static Register(pContext: vscode.ExtensionContext): XGeneratedFileGuard {
        const guard = new XGeneratedFileGuard();

        guard._Disposables.push(
            vscode.window.onDidChangeActiveTextEditor(editor => { void guard.ProtectIfGenerated(editor); })
        );
        pContext.subscriptions.push(...guard._Disposables);

        // O editor já ativo no momento da ativação também passa pela guarda.
        void guard.ProtectIfGenerated(vscode.window.activeTextEditor);

        return guard;
    }

    /** Ligado por padrão; desligável em `dase.protectGeneratedFiles`. */
    private IsEnabled(): boolean {
        return vscode.workspace.getConfiguration("dase").get<boolean>("protectGeneratedFiles", true);
    }

    /** True quando o texto do cabeçalho traz o marcador de arquivo gerado. */
    static IsGenerated(pHeadText: string): boolean {
        return XGeneratedFileGuard.MARKER.test(pHeadText);
    }

    async ProtectIfGenerated(pEditor: vscode.TextEditor | undefined): Promise<void> {
        if (!pEditor || !this.IsEnabled())
            return;

        const doc = pEditor.document;
        // Só arquivos reais em disco: o designer `.dsorm` é um editor custom (webview) e não chega
        // aqui, e documentos untitled/virtuais não são código gerado.
        if (doc.uri.scheme !== "file")
            return;

        if (!XGeneratedFileGuard.IsGenerated(doc.getText().slice(0, XGeneratedFileGuard.HEAD)))
            return;

        try {
            await vscode.commands.executeCommand(XGeneratedFileGuard.READONLY_COMMAND);
        }
        catch (err) {
            // Comando ausente numa build do VS Code sem o recurso: registra e segue — a proteção é
            // um reforço, não pode derrubar a ativação nem a troca de editor.
            GetLogService().Error("GeneratedFileGuard: failed to set editor read-only", err);
        }
    }
}
