import * as vscode from "vscode";
import { XGeneratedFileGuard } from "../../Services/GeneratedFileGuard";

jest.mock("vscode");

const READONLY_COMMAND = "workbench.action.files.setActiveEditorReadonlyInSession";

/** Editor falso com o texto e o esquema de URI dados. */
function MockEditor(pText: string, pScheme = "file"): any {
    return {
        document: {
            uri: { scheme: pScheme },
            getText: () => pText
        }
    };
}

const GENERATED = "// <auto-generated>\n//     Gerado pelo DASE a partir do modelo ORM. NÃO EDITE ESTE ARQUIVO.\nclass X {}";
const HANDWRITTEN = "// Escrito à mão\npublic partial class X { }";

describe("XGeneratedFileGuard", () => {

    beforeEach(() => {
        jest.clearAllMocks();
        // Config: habilitado por padrão (o get devolve o default passado).
        (vscode.workspace.getConfiguration as jest.Mock).mockReturnValue({
            get: (_k: string, d?: unknown) => d
        });
    });

    describe("IsGenerated", () => {
        it("reconhece o marcador <auto-generated>", () => {
            expect(XGeneratedFileGuard.IsGenerated(GENERATED)).toBe(true);
        });

        it("é indiferente à caixa do marcador", () => {
            expect(XGeneratedFileGuard.IsGenerated("// <AUTO-GENERATED>")).toBe(true);
        });

        it("não marca arquivo escrito à mão", () => {
            expect(XGeneratedFileGuard.IsGenerated(HANDWRITTEN)).toBe(false);
        });
    });

    describe("ProtectIfGenerated", () => {

        it("trava o editor de um arquivo gerado", async () => {
            const guard = new XGeneratedFileGuard();
            await guard.ProtectIfGenerated(MockEditor(GENERATED));

            expect(vscode.commands.executeCommand).toHaveBeenCalledWith(READONLY_COMMAND);
        });

        it("não trava um arquivo escrito à mão", async () => {
            const guard = new XGeneratedFileGuard();
            await guard.ProtectIfGenerated(MockEditor(HANDWRITTEN));

            expect(vscode.commands.executeCommand).not.toHaveBeenCalled();
        });

        it("ignora quando não há editor", async () => {
            const guard = new XGeneratedFileGuard();
            await guard.ProtectIfGenerated(undefined);

            expect(vscode.commands.executeCommand).not.toHaveBeenCalled();
        });

        it("ignora documentos que não são arquivos em disco", async () => {
            const guard = new XGeneratedFileGuard();
            await guard.ProtectIfGenerated(MockEditor(GENERATED, "untitled"));

            expect(vscode.commands.executeCommand).not.toHaveBeenCalled();
        });

        it("não trava quando a proteção está desligada", async () => {
            (vscode.workspace.getConfiguration as jest.Mock).mockReturnValue({ get: () => false });

            const guard = new XGeneratedFileGuard();
            await guard.ProtectIfGenerated(MockEditor(GENERATED));

            expect(vscode.commands.executeCommand).not.toHaveBeenCalled();
        });

        it("engole erro do comando sem propagar", async () => {
            (vscode.commands.executeCommand as jest.Mock).mockRejectedValueOnce(new Error("comando ausente"));

            const guard = new XGeneratedFileGuard();
            await expect(guard.ProtectIfGenerated(MockEditor(GENERATED))).resolves.toBeUndefined();
        });
    });

    describe("Register", () => {

        it("assina a troca de editor ativo e devolve a guarda", () => {
            const subscriptions: any[] = [];
            const guard = XGeneratedFileGuard.Register({ subscriptions } as any);

            expect(guard).toBeInstanceOf(XGeneratedFileGuard);
            expect(vscode.window.onDidChangeActiveTextEditor).toHaveBeenCalledTimes(1);
            expect(subscriptions.length).toBeGreaterThan(0);
        });

        it("passa o editor já ativo pela guarda na ativação", async () => {
            (vscode.window as any).activeTextEditor = MockEditor(GENERATED);

            XGeneratedFileGuard.Register({ subscriptions: [] } as any);
            // ProtectIfGenerated roda sem await dentro do Register; drena a microtask.
            await Promise.resolve();
            await Promise.resolve();

            expect(vscode.commands.executeCommand).toHaveBeenCalledWith(READONLY_COMMAND);
            (vscode.window as any).activeTextEditor = undefined;
        });

        it("trava quando o editor recém-ativado é gerado", async () => {
            let captured: ((e: unknown) => void) | undefined;
            (vscode.window.onDidChangeActiveTextEditor as jest.Mock).mockImplementation((cb: (e: unknown) => void) => {
                captured = cb;
                return { dispose: () => { } };
            });

            XGeneratedFileGuard.Register({ subscriptions: [] } as any);
            captured?.(MockEditor(GENERATED));
            await Promise.resolve();
            await Promise.resolve();

            expect(vscode.commands.executeCommand).toHaveBeenCalledWith(READONLY_COMMAND);
        });
    });
});
